# Generated by Django 5.0.2 on 2024-03-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0002_feedback_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingstatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'bookingstatus',
                'managed': False,
            },
        ),
    ]
